platform :ios
pod 'Reachability',  '~> 3.0.0'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'sqlite3', '~> 3.8.10.2'
pod 'RegexKitLite', '~> 4.0'
pod 'BaiduMapAPI', '~> 2.7.0'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'yajl-objc', '~> 0.2.27'
pod 'iOSWeChatSdk', '~> 1.5.0'


pod 'cJSON',:podspec => '~/Desktop/PodSpecs/PodSpecs/cJSON.podspec'
pod 'cUPYun',:podspec => '~/Desktop/PodSpecs/PodSpecs/cUPYun.podspec'
pod 'DES',:podspec => '~/Desktop/PodSpecs/PodSpecs/DES.podspec'
pod 'GTM',:podspec => '~/Desktop/PodSpecs/PodSpecs/GTM.podspec'
pod 'iOScURL',:podspec => '~/Desktop/PodSpecs/PodSpecs/iOScURL.podspec'
pod 'MLNavigationController',:podspec => '~/Desktop/PodSpecs/PodSpecs/MLNavigationController.podspec'
pod 'UIView-Image',:podspec => '~/Desktop/PodSpecs/PodSpecs/UIView-Image.podspec'
pod 'ZCAddressBook',:podspec => '~/Desktop/PodSpecs/PodSpecs/ZCAddressBook.podspec'